### ISSUE TITLE
Remove Bats

### ISSUE THREAD

**Issue by connor7000** [mc-ascendancy/ascendancy#59]
From **NotARobot2#0448** on Discord:

"Remove bats."

(Really? @NotARobotII 👎)

**Comment by VolticFroogo** [comment]
Yikes, this one is very weird, given that it's NAR, I'd kinda like to here his perspective before closing this one.

**Comment by NotARobotII** [comment]
I hate bats, why do they get their own mob category? Since version 1.4.2 the "Ambient" mob category has been in the game, and since then, bats have been the only ones in that category. All they do is spawn in underground areas, and fly around with their stupid little hitbox and make annoying sounds. No-one would care if they were erased from existence.

TL:DR : I hate minecraft bat's very existence.

**Comment by VolticFroogo** [comment]
*Yikes!* Okay, yeah, Connor was right about closing this one. haha
